-- MySQL Script generated by MySQL Workbench
-- Tue Aug 15 21:48:26 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bio` DEFAULT CHARACTER SET utf8 ;
USE `bio` ;

-- -----------------------------------------------------
-- Table `bio`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bio`.`user` ;

CREATE TABLE IF NOT EXISTS `bio`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NULL DEFAULT 'LV',
  `language` VARCHAR(45) NULL DEFAULT 'LV',
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `photo` TEXT NULL,
  `role` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL DEFAULT 'active',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bio`.`subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bio`.`subject` ;

CREATE TABLE IF NOT EXISTS `bio`.`subject` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `alias` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL DEFAULT 'LV',
  `language` VARCHAR(45) NULL DEFAULT 'LV',
  `name` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL DEFAULT 'active',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `u2` (`alias` ASC, `language` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bio`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bio`.`course` ;

CREATE TABLE IF NOT EXISTS `bio`.`course` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `alias` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL DEFAULT 'LV',
  `language` VARCHAR(45) NULL DEFAULT 'LV',
  `name` VARCHAR(45) NULL,
  `subject_alias` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NULL DEFAULT 'active',
  PRIMARY KEY (`id`, `subject_alias`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bio`.`material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bio`.`material` ;

CREATE TABLE IF NOT EXISTS `bio`.`material` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `alias` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL DEFAULT 'LV',
  `language` VARCHAR(45) NULL DEFAULT 'LV',
  `name` VARCHAR(45) NULL,
  `course_alias` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL DEFAULT 'active',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bio`.`user_material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bio`.`user_material` ;

CREATE TABLE IF NOT EXISTS `bio`.`user_material` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `material_alias` VARCHAR(45) NULL,
  `complete` VARCHAR(45) NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
